name: 'netflix_elt'
version: '1.0.0'
profile: 'dbt_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  netflix_elt:

    staging:
      +materialized: view
      +schema: STAGING

    intermediate:
      +materialized: view
      +schema: INTERMEDIATE

    marts:
      +materialized: table
      +schema: MARTS