-- DATABASE
CREATE DATABASE IF NOT EXISTS DBT_SNOWFLAKE_DEV;

-- SCHEMAS
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.MARTS;

-- WAREHOUSE (if you don't have one)
CREATE WAREHOUSE IF NOT EXISTS DBT_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- ROLE
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- Give DBT_ROLE full access
GRANT ALL ON DATABASE DBT_SNOWFLAKE_DEV TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE DBT_SNOWFLAKE_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DBT_SNOWFLAKE_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE DBT_SNOWFLAKE_DEV TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;

-- Assign role to your user
GRANT ROLE DBT_ROLE TO USER YOUR_SNOWFLAKE_USERNAME;